steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mcp-gateway', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mcp-gateway']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mcp-gateway'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mcp-gateway'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MCP_GATEWAY_DEMO_MODE=true,GEMINI_MODEL=gemini-3-flash-preview'
      - '--set-secrets'
      - 'GOOGLE_API_KEY=google-api-key:latest,MCP_GATEWAY_ADMIN_TOKEN=admin-token:latest'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '3'
      - '--timeout'
      - '300'

substitutions:
  _REGION: asia-northeast1

images:
  - 'gcr.io/$PROJECT_ID/mcp-gateway'
